name: z_flutter
description: A new Flutter package project.
version: 1.0.0-dev.18
homepage:

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

  z_dart:
    git:
      url: https://github.com/zemoga/z_dart.git
      ref: 1.0.0-dev.17

  path_provider: ^2.0.8
  shared_preferences: ^2.0.11
  url_launcher: ^6.0.17
  share_plus: ^4.0.1
  package_info_plus: ^1.0.6
  lottie: ^1.2.0
  flutter_svg: ^1.0.0
  sliver_tools: ^0.2.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
