name: z_flutter
description: A new Flutter package project.
version: 1.0.0-dev.31
homepage:

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  lottie: ^2.5.0
  flutter_svg: ^2.0.7
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
